/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    java
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://oss.sonatype.org/content/repositories/snapshots")
    }

    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    implementation("commons-httpclient:commons-httpclient:3.1")
    implementation("org.slf4j:slf4j-api:1.5.2")
    testImplementation("junit:junit:4.13.1")
    compileOnly("javax.servlet:servlet-api:2.4")
    compileOnly("ant:ant:1.5")
}

group = "org.tuckey"
version = "5.0.0-SNAPSHOT"
description = "UrlRewriteFilter"
java.sourceCompatibility = JavaVersion.VERSION_1_5

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}
